name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    # paths:
    #   - 'api/Dockerfile'
    #   - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t abbysac/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t abbysac/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u abbysac -p ${{ secrets.DOCKEER_HUB_SECRET }}
          docker push abbysac/devops-qr-code-backend:latest
          docker push abbysac/devops-qr-code-frontend:latest
      - name: Create temporary directory
        run: mkdir -p ./app
      - name: Download jar files from S3
        run: |
          mkdir s3-files
          aws s3 sync ./packages3.json s3://cca670-tickitdb/jar  
        #./app/jar
    #   - name: Create Dockerfile
    #     run: |
    #       cat <<EOF > Dockerfile
    #       FROM openjdk:17-jdk-slim
    #       WORKDIR /app
    #       COPY ./app/jar /app/jar
    #       CMD ["java", "-jar", "/app/jar/your-file.jar"]
    #       EOF
    #   - name: Build Docker Image
    #     run: |
    #       docker build -t docker push abbysac/devops-qr-code-backend:latest
    #       docker push abbysac/devops-qr-code-frontend:latest 