name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JFROG_REGISTRY }}
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "FROM node:18" > Dockerfile.temp
          echo "WORKDIR /app" >> Dockerfile.temp
          echo "COPY package*.json ./" >> Dockerfile.temp
          echo "RUN npm install" >> Dockerfile.temp
          echo "COPY . ." >> Dockerfile.temp
          echo "EXPOSE 3000" >> Dockerfile.temp
          echo "CMD [\"node\", \"index.js\"]" >> Dockerfile.temp
          docker buildx build --platform linux/amd64 -t ${{ secrets.JFROG_REGISTRY }}/docker-local/my-app:${{ github.sha }} -f Dockerfile.temp --push .
          rm Dockerfile.temp

      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: <your-username>/my-app-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifest-repo

      - name: Update image tag in manifest
        run: |
          sed -i 's|image:.*$|image: ${{ secrets.JFROG_REGISTRY }}/docker-local/my-app:${{ github.sha }}|' manifest-repo/k8s/deployment.yaml
          cd manifest-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push